---
- name: Install httpd package
  yum:
    name: httpd
    state: present

- name: Ensure httpd is enabled and started
  service:
    name: httpd
    state: started
    enabled: yes

- name: Deploy vhost configuration from template
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/myvhost.conf

- name: Reload httpd
  meta: refresh_inventory
