- name: Instalar y asegurar que httpd esté instalado
  yum:
    name: httpd
    state: present
  become: true

- name: Habilitar y arrancar el servicio httpd
  service:
    name: httpd
    state: started
    enabled: true
  become: true

- name: Crear directorio web
  file:
    path: /var/www/web
    state: directory
    owner: apache
    group: apache
    mode: '0755'
  become: true

- name: Copiar archivo index.html
  copy:
    src: files/index.html
    dest: /var/www/web/index.html
    owner: apache
    group: apache
    mode: '0644'
  become: true

- name: Configurar VirtualHost de Apache
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/web_virtualhost.conf
  notify: Reiniciar httpd
  become: true

- name: Permitir tráfico HTTP en firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes
  become: true

- name: Asegurar firewalld está activo
  service:
    name: firewalld
    state: started
    enabled: true
  become: true
